name: CI Pipeline

on:
  push:
    branches:
      - main  

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]  
    runs-on: ${{ matrix.os }}  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Faz o checkout do código

      - name: Send HTTP POST to Jenkins using curl
        run: |
          curl -X POST "http://191.101.78.132:8080/job/backend_tecmed/build/WithParameters?token=rochaCorporation" \
               --data "username=${{ secrets.JENKINS_USERNAME }}" \
               --data "password=${{ secrets.JENKINS_PASSWORD }}"
